name: Build

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup GCC 12
        uses: actions/setup-gcc@v1
        with:
          gcc-version: '12'

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_STANDARD_REQUIRED=ON

      - name: Build
        run: cmake --build build --config Release --parallel 8
