name: Build

on: 
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install GCC 13
      run: sudo apt-get update && sudo apt-get install -y g++-13 && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 60

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_STANDARD_REQUIRED=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release --parallel 8
